fix_permission_denied:
	chmod +x update.sh
	chmod +x create.sh

deploy:
	sh create.sh udagram final-project-starter.yml server-parameters.json &&\
	sh create.sh udagram final-project-starter-server.yml server-parameters.json